services:
  - type: web
    name: cms-uni
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYLOAD_CONFIG_PATH
        value: dist/payload.config.js
